on: push
name: Deploy to GitHub Organization Pages
jobs:
  filtersForGitHubActions:
    name: Filters for GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    # - name: Filters for GitHub Actions
    #   uses: actions/bin/filter@master
    #   with:
    #     args: branch master
    - name: Publish Site
      uses: peaceiris/actions-hugo@v2
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        extended: true
