on: push
name: Deploy to GitHub Organization Pages
jobs:
  filtersForGitHubActions:
    name: Filters for GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    # - name: Filters for GitHub Actions
    #   uses: actions/bin/filter@master
    #   with:
    #     args: branch master
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.PERSONAL_TOKEN }}
        cname: faximili.me
        repo: faximilie/faximilie.github.io
